### ISSUE TITLE
RedisInsight ERROR after adding a node to an existing cluster (incorrect data added to nodes field in instances table in db dict )

### ISSUE THREAD

**Issue by marksullivancrowd** [RedisLabs/redislabs-docs#1269]
RedisInsight version 1.10.0

```
ERROR 2021-03-09 22:27:58,624 django.request Internal Server Error: /api/instance/e27487cc-089f-45ab-be0d-ab8ce6918278/redis-info/
Traceback (most recent call last):
  File "./redisinsight/core/models.py", line 334, in validate_cluster_nodes
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/decorators.py", line 54, in handler
    return func(*args, **kwargs)
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/monitoring/views.py", line 153, in get_overview_info
  File "./redisinsight/core/services/database/_routines.py", line 923, in get_saved_db
  File "./redisinsight/core/services/database/_routines.py", line 915, in _orm_obj_to_saved_db
  File "./redisinsight/core/services/database/_entities.py", line 340, in __init__
  File "./redisinsight/core/models.py", line 655, in get_cluster_seed_nodes
  File "./redisinsight/core/models.py", line 336, in validate_cluster_nodes
ValueError: Each dict in the iterable should have items 'host' (str) and 'port' (int), got {'host': '(IP)', 'port': '(nonstandardPort)', 'username': '', 'password': '', 'ssl': False}
ERROR 2021-03-09 22:28:01,342 django.request Internal Server Error: /api/instance/e27487cc-089f-45ab-be0d-ab8ce6918278/cluster-alerts/
Traceback (most recent call last):
  File "./redisinsight/core/models.py", line 334, in validate_cluster_nodes
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/decorators.py", line 54, in handler
    return func(*args, **kwargs)
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/cluster_management/decorators.py", line 40, in _wrapped_view
  File "./redisinsight/cluster_management/views.py", line 284, in cluster_alerts
  File "./redisinsight/cluster_management/services/api.py", line 168, in get_actual_migration_plan
  File "./redisinsight/core/services/database/_routines.py", line 923, in get_saved_db
  File "./redisinsight/core/services/database/_routines.py", line 915, in _orm_obj_to_saved_db
  File "./redisinsight/core/services/database/_entities.py", line 340, in __init__
  File "./redisinsight/core/models.py", line 655, in get_cluster_seed_nodes
  File "./redisinsight/core/models.py", line 336, in validate_cluster_nodes
ValueError: Each dict in the iterable should have items 'host' (str) and 'port' (int), got {'host': '(IP)', 'port': '(nonstandardPort)', 'username': '', 'password': '', 'ssl': False}

```

looking at the sqlite db it should be only adding {'host': '(IP)', 'port': '(nonstandardPort)'}
but its adding
{'host': '(IP)', 'port': '(nonstandardPort)', 'username': '', 'password': '', 'ssl': False}

to the "nodes" text in the instances table of the sqlite 
using 
https://hub.docker.com/layers/redislabs/redisinsight/latest/images/sha256-71d0291d64fa76158cb4c5743c88d56922299c4d7bfe53e996b8c8eafaa4897e?context=explore
of redisinsight image built march 8th 2021

fixed by manually updating the db

`UPDATE instances SET nodes = '[{"host": "(IP)", "port": (nonstandardPort)}, {"host": "(IP)", "port": (nonstandardPort)}]' WHERE id = 1;`

**Comment by GnaneshKunal** [comment]
Hey @marksullivancrowd, looking into this and will get back to you.

**Comment by lanceleonard** [comment]
Hi @marksullivancrowd!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
