### ISSUE TITLE
RedisInsight v1.4.0 fails to start - "Requires an IP to get the server name"

### ISSUE THREAD

**Issue by tayler-king** [RedisLabs/redislabs-docs#790]
Apologies if I have opened this in the incorrect place, it seems like there are a couple of other RedisInsight issues opened here.

Anyhow, RedisInsight decided it wanted to stop starting for seemingly no reason at all. Here's the full logs:

```console
INFO 2020-05-04 12:12:53,474 redisinsight_startup Registered SIGTERM handler
INFO 2020-05-04 12:12:53,695 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:12:54,843 redisinsight_startup Operations to perform:

INFO 2020-05-04 12:12:54,843 redisinsight_startup   Apply all migrations: admin, auth, authtoken, browser, cluster_management, contenttypes, core, memory_analysis, profiling, recommendation, sessions

INFO 2020-05-04 12:12:54,868 redisinsight_startup Running migrations:

INFO 2020-05-04 12:12:54,868 redisinsight_startup   No migrations to apply.

INFO 2020-05-04 12:12:55,025 redisinsight_startup Starting waitress
ERROR 2020-05-04 12:12:55,032 redisinsight_startup Error running web app
Traceback (most recent call last):
  File "startup.py", line 104, in run_web_app
  File "startup.py", line 88, in start_webserver
  File "site-packages\waitress\__init__.py", line 12, in serve
  File "site-packages\waitress\server.py", line 88, in create_server
  File "site-packages\waitress\server.py", line 242, in __init__
  File "site-packages\waitress\server.py", line 254, in get_server_name
ValueError: Requires an IP to get the server name
INFO 2020-05-04 12:12:55,704 redisinsight_startup not up yet
INFO 2020-05-04 12:12:56,704 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:12:58,709 redisinsight_startup not up yet
INFO 2020-05-04 12:12:59,710 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:01,714 redisinsight_startup not up yet
INFO 2020-05-04 12:13:02,714 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:04,718 redisinsight_startup not up yet
INFO 2020-05-04 12:13:05,718 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:07,724 redisinsight_startup not up yet
INFO 2020-05-04 12:13:08,725 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:10,732 redisinsight_startup not up yet
INFO 2020-05-04 12:13:11,732 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:13,737 redisinsight_startup not up yet
INFO 2020-05-04 12:13:14,738 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:16,744 redisinsight_startup not up yet
INFO 2020-05-04 12:13:17,744 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:19,750 redisinsight_startup not up yet
INFO 2020-05-04 12:13:20,750 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:22,756 redisinsight_startup not up yet
INFO 2020-05-04 12:13:23,756 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:25,768 redisinsight_startup not up yet
INFO 2020-05-04 12:13:26,770 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:28,773 redisinsight_startup not up yet
INFO 2020-05-04 12:13:29,774 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:31,780 redisinsight_startup not up yet
INFO 2020-05-04 12:13:32,780 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:34,784 redisinsight_startup not up yet
INFO 2020-05-04 12:13:35,785 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:37,790 redisinsight_startup not up yet
INFO 2020-05-04 12:13:38,790 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:40,796 redisinsight_startup not up yet
INFO 2020-05-04 12:13:41,797 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:43,804 redisinsight_startup not up yet
INFO 2020-05-04 12:13:44,805 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:46,810 redisinsight_startup not up yet
INFO 2020-05-04 12:13:47,811 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:49,816 redisinsight_startup not up yet
INFO 2020-05-04 12:13:50,816 redisinsight_startup Checking if server running at http://127.0.0.1:8099 is up...
INFO 2020-05-04 12:13:52,821 redisinsight_startup not up yet
ERROR 2020-05-04 12:13:53,821 redisinsight_startup Error in main()
Traceback (most recent call last):
  File "startup.py", line 324, in main_ui
  File "startup.py", line 222, in create_and_run_ui
  File "startup.py", line 135, in wait_for_server_to_start
Exception: Could not start web server even after 60 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "startup.py", line 475, in main
  File "startup.py", line 333, in main_ui
  File "startup.py", line 259, in ctype_async_raise
ValueError: Invalid thread object
```

I've tried manually binding the port + host with the appropriate environment variables yet it doesn't seem to help.

**Comment by GnaneshKunal** [comment]
@tayler-king RedisInsight v1.11 was released and the problem must have been probably fixed. Can you try it with v1.11?

Also the problem is that your host might not be set to 127.0.0.1 or localhost. If you are on linux you can check `/etc/hosts` file and there should be a following entry:
```
127.0.0.1       localhost
```

If you know your hostname, you can just pass your hostname in host environment variable, i.e, `RIHOST=MY-DESKTOP` and access the redisinsight at `http://MY-DESKTOP:<RIPORT>`.

**Comment by lanceleonard** [comment]
Hi @tayler-king!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
