### ISSUE TITLE
Adding redis sentinel not work on RedisInsight

### ISSUE THREAD

**Issue by Steuf** [RedisLabs/redislabs-docs#833]
**Current behavior**
Unable to add a redis sentinel database after select the master node

**Expected behavior** 
Adding sentinel to database

**Screenshots** 
<img width="763" alt="Capture d’écran 2020-05-20 à 12 57 39" src="https://user-images.githubusercontent.com/262871/82438570-8f1df380-9a99-11ea-8e6f-e61f44476bad.png">

**Additional context** 

It's on a Kubernetes cluster with stable/redis-ha helm chart with sentinel. Connexion is ok but when I choose the master server, I have a 500 error on the api.

Tested with version 1.5.0, 1.4.0, 1.3.0... Redis server 5.0.9-alpine.

**Comment by bmansheim** [comment]
Thanks for reaching out to us, @Steuf .
@slemeur Can you comment on this issue?

**Comment by slemeur** [comment]
We need to investigate this issue.
cc @nishantgeorge @Arushi201296

**Comment by Arushi201296** [comment]
@Steuf May I know what appears in the logs/network console preview when you try to add such a database?

**Comment by Steuf** [comment]
Yes off course, the first query on adding the sentinel server before choose the master :

<img width="1144" alt="Capture d’écran 2020-05-21 à 17 10 13" src="https://user-images.githubusercontent.com/262871/82573470-19438600-9b86-11ea-8c78-9355f7c73198.png">

And params and server response when I choose the master server:

<img width="671" alt="Capture d’écran 2020-05-21 à 17 10 33" src="https://user-images.githubusercontent.com/262871/82573514-2b252900-9b86-11ea-8dea-fe8db6fbecb5.png">

<img width="1149" alt="Capture d’écran 2020-05-21 à 17 10 21" src="https://user-images.githubusercontent.com/262871/82573526-2eb8b000-9b86-11ea-95cd-d35d4854db55.png">

**Comment by Steuf** [comment]
And the internal error on logs : 

```
ERROR 2020-05-21 15:38:51,376 django.request Internal Server Error: /api/instance/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "./redisinsight/core/views/instance.py", line 203, in post
  File "./redisinsight/core/views/instance.py", line 143, in _save_redis_instance
  File "./redisinsight/core/services/database/_routines.py", line 64, in _wrapped_add_db_func
  File "./redisinsight/core/services/database/_routines.py", line 640, in add_redis_database
  File "./redisinsight/core/services/database/_routines.py", line 673, in add_sentinel_monitored_db
  File "./redisinsight/core/services/database/_routines.py", line 332, in _add_sentinel_monitored_db
  File "./redisinsight/core/services/database/_routines.py", line 243, in _probe_other_sentinel_nodes_info
  File "./redisinsight/core/services/database/_routines.py", line 243, in <setcomp>
KeyError: 'host'
```

**Comment by Raghavendarlokineni** [comment]
Hi, I am also facing the same issue while adding sentinel database.

Info:
Redis - 5.0.8
redisinsight-linux64-1.5.0
OS - Red Hat Enterprise Linux Server 7.8 (Maipo)

**Comment by Steuf** [comment]
Hi guys,

Any news for the fix ?

**Comment by slemeur** [comment]
We have been able to reproduce the issue - so we'll investigate the problem and provide a fix soon.

Thanks for reaching out and letting us know about your issue!

**Comment by benjie91** [comment]
Facing similar issue but I was using bitnami/redis helm chart

**Comment by slemeur** [comment]
@benjie91: Thanks for letting us know, we'll test that as well.

**Comment by corey-hammerton** [comment]
We are facing the same problem as @benjie91 on the bitnami/redis Helm Chart. Is there any update on this fix?

**Comment by corey-hammerton** [comment]
For additional information, we are running version 1.8.3 of Redis Insight

**Comment by StupidHobbit** [comment]
Hey everyone, faced same problem with Redis Insight 1.9.0

**Comment by nishantgeorge** [comment]
@StupidHobbit Can you share some details about your setup, like which OS you are using RedisInsight on (Mac/Windows/Linux/Docker), how and where the Redis Sentinel cluster is deployed, etc.

**Comment by StupidHobbit** [comment]
@nishantgeorge I'm using laptop with Ubuntu 18.04. Redis Sentinel is deployed with [Yandex Managed Service for Redis](https://cloud.yandex.com/services/managed-redis

**Comment by nishantgeorge** [comment]
@StupidHobbit Thanks for the information.

Currently, RedisInsight is not tested with Yandex, but assuming it behaves like a normal properly-configured Redis Sentinel cluster, it _should_ work.

I've taken it down as something we have to investigate, and we'll get back to you when we figure out what the issue is here.

**Comment by corey-hammerton** [comment]
Is there an update for this issue for Redis Sentinel? @nishantgeorge

**Comment by nishantgeorge** [comment]
@corey-hammerton We are still unable to reproduce the issue properly. It would be super helpful if you could provide the exact steps to reproduce the issue, including your setup in k8s.

**Comment by corey-hammerton** [comment]
K8s Version: 1.17.13 (GKE)
Redis Insight Version: 1.8.3
Version of Redis App: 6.0.11
Version of Redis Sentinel: 6.0.11
Username/password: N/A
TLS: N/A

Steps to reproduce:

1. Redis Insight UI -> Add Redis Database
2. Connect to a Redis Database
3. Host: <redis_svc>
4. Port: 26379
5. Name: <redis_svc>
6. Username & Password: Leave blank
7. Redis Sentinel instance found -> Add Selected Database
8. Something went wrong adding the sentinel database

```
ERROR 2021-03-17 16:38:11,985 django.request Internal Server Error: /api/instance/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "./redisinsight/core/views/instance.py", line 208, in post
  File "./redisinsight/core/views/instance.py", line 147, in _save_redis_instance
  File "./redisinsight/core/services/database/_routines.py", line 80, in _wrapped_add_db_func
  File "./redisinsight/core/services/database/_routines.py", line 787, in add_redis_database
  File "./redisinsight/core/services/database/_routines.py", line 826, in add_sentinel_monitored_db
  File "./redisinsight/core/services/database/_routines.py", line 393, in _add_sentinel_monitored_db
  File "./redisinsight/core/services/database/_routines.py", line 282, in _probe_other_sentinel_nodes_info
  File "./redisinsight/core/services/database/_routines.py", line 282, in <setcomp>
KeyError: 'host'
```

Apologies for the late reply

**Comment by nishantgeorge** [comment]
@corey-hammerton Thank you! We will try this and let you know soon.

**Comment by wpirraglia** [comment]
Hi:
I'm facing the same issue with a basic docker env configuration (3 docker containers, running both redis server and sentinel in the same container), trying to add the db programatically.
When trying to add the server through the UI, it displays the same error as reported initially.

**Comment by samcarpentier** [comment]
@ollopaci @K-Jo Any ETA on this one? I tried every RedisInsight from 1.2.0 to the latest 1.10.1 and this bug seems to have always been there...

**Comment by jelmokri** [comment]
Any news ? facing the same issue with redisinsight in a docker and Redis server and sentinel on the same server but not in docker

**Comment by jawabuu** [comment]
@nishantgeorge @slemeur I'm able to reproduce this consistently.
On the other hand, connecting `STANDALONE` & `CLUSTER` connectionType works fine.

**Comment by revathyr13** [comment]
@nishantgeorge  @slemeur  @banker  I am also able to reproduce the same error for redis-sentinel failover cluster

**Comment by lanceleonard** [comment]
Hi everyone!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
